# Generated by Django 5.0.6 on 2024-07-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('dc_comics', 'DC Comics'), ('marvel_comics', 'MARVEL Comics'), ('mangas', 'MANGAS')], default='dc_comics', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
    ]
